"""user theme preference

Revision ID: d4d9c5b96249
Revises: 8ae7e5d0d8c9
Create Date: 2026-07-18 21:10:25.950817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4d9c5b96249"
down_revision: Union[str, Sequence[str], None] = "8ae7e5d0d8c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default="system": the table already has rows (every prior
    # story's Administrator accounts) by the time this NOT NULL column
    # lands — a Python-side default alone doesn't help an ALTER TABLE
    # against existing data, same gotcha as 8ae7e5d0d8c9's
    # failed_login_count.
    op.add_column(
        "users",
        sa.Column("theme_preference", sa.String(), nullable=False, server_default="system"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "theme_preference")
    # ### end Alembic commands ###
