"""sales and reference data ingestion

Revision ID: e054c35b938f
Revises: d4d9c5b96249
Create Date: 2026-07-19 05:40:15.658883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e054c35b938f"
down_revision: Union[str, Sequence[str], None] = "d4d9c5b96249"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # All tables below are brand new (freshly created, no existing rows), so
    # the server_default-on-NOT-NULL-column-of-a-non-empty-table gotcha that
    # bit 8ae7e5d0d8c9/d4d9c5b96249 does not apply here.
    op.create_table(
        "brand_performance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_brand_id", sa.String(), nullable=False),
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("sales", sa.Numeric(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("growth_pct", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_brand_id"),
    )
    op.create_table(
        "doctors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_doctor_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("territory", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("external_doctor_id"),
    )
    op.create_table(
        "import_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_processed", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sales_data",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("sales_amount", sa.Numeric(), nullable=False),
        sa.Column("achievement_pct", sa.Numeric(), nullable=False),
        sa.Column("growth_pct", sa.Numeric(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date", "team_id"),
    )
    op.create_table(
        "staging_brand_performance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("raw_external_brand_id", sa.String(), nullable=True),
        sa.Column("raw_brand_name", sa.String(), nullable=True),
        sa.Column("raw_sales", sa.String(), nullable=True),
        sa.Column("raw_rank", sa.String(), nullable=True),
        sa.Column("raw_growth_pct", sa.String(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_run_id"], ["import_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_run_id", "sequence"),
    )
    op.create_table(
        "staging_doctors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("raw_external_doctor_id", sa.String(), nullable=True),
        sa.Column("raw_name", sa.String(), nullable=True),
        sa.Column("raw_territory", sa.String(), nullable=True),
        sa.Column("raw_priority", sa.String(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_run_id"], ["import_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_run_id", "sequence"),
    )
    op.create_table(
        "staging_sales_data",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("import_run_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("raw_date", sa.String(), nullable=True),
        sa.Column("raw_team", sa.String(), nullable=True),
        sa.Column("raw_sales_amount", sa.String(), nullable=True),
        sa.Column("raw_achievement_pct", sa.String(), nullable=True),
        sa.Column("raw_growth_pct", sa.String(), nullable=True),
        sa.Column("is_valid", sa.Boolean(), nullable=True),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_run_id"], ["import_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_run_id", "sequence"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("staging_sales_data")
    op.drop_table("staging_doctors")
    op.drop_table("staging_brand_performance")
    op.drop_table("sales_data")
    op.drop_table("teams")
    op.drop_table("import_runs")
    op.drop_table("doctors")
    op.drop_table("brand_performance")
    # ### end Alembic commands ###
